Sample example
asas1asas200/NTOUClassroomBorrowing pull request #4
Opened 2022-10-13 11:29 UTC by lin121291

- 新增src底下目錄
- 簡單的example

2022-10-13 12:20 UTC, asas1asas200 commented
Related issues: #3

2022-10-14 10:50 UTC, lin121291 commented
ok 謝啦 我晚點push更改

2022-10-15 18:36 UTC, asas1asas200 commented on .gitignore
> +.keep
Use `.keep` instead `tmp.js`

2022-10-16 14:47 UTC, lin121291 commented
我更新了

2022-10-16 17:48 UTC, asas1asas200 commented
You should add them back and commit again, otherwise this program cannot build.

And use `.keep` instead `tmp.js`.

2022-10-17 05:46 UTC, asas1asas200 requested changes

2022-10-17 05:46 UTC, asas1asas200 commented on README.md
> +
This command failed as below:
```
$ node build
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '/home/zeng/Desktop/NTOUClassroomBorrowing/src/build'
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.11.0
```

Use `npm install` instead.

2022-10-17 05:46 UTC, asas1asas200 commented on README.md
> +# Get npm package
The README is an important document, so you should write more rigorous, such as consistent capital in each line.

2022-10-17 07:24 UTC, asas1asas200 approved these changes

2022-10-17 07:27 UTC, merged