add profile edit page and route to profile edit page
asas1asas200/NTOUClassroomBorrowing pull request #42
Opened 2022-11-13 11:01 UTC by Argentum11

## Types of changes
**Thanks for sending a pull request! Please fill in the following content to let us know better about this change.**
Please put an `x` in the box that applies

- [ ] **Bugfix**
- [x] **New feature**
- [ ] **Refactoring**
- [ ] **Breaking change** (any change that would cause existing functionality to not work as expected)
- [ ] **Documentation Update**
- [ ] **Other (please describe)**

## Description
1. Add profile edit page
2. Add route to profile edit page

## Steps to Test This Pull Request
Steps to reproduce the behavior:
1. Go to main page
3. Click on your account name ( root or any account you register)
4. Select  'Edit Profile'

## Expected behavior
display text "this is profile edit page"

## Related Issue
partial #37 

## More Information
I don't know if putting profile as the same level of admin is correct

2022-11-13 13:04 UTC, asas1asas200 commented on src/app.js
> +app.use("/profile",profileRouter)
It should add a space after comma here.
You can use [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) to help you format the code.

2022-11-13 16:34 UTC, Argentum11 commented on src/app.js
> +app.use("/profile",profileRouter)
Ok, I made a new commit to fix the problem

2022-11-20 09:02 UTC, asas1asas200 requested changes

2022-11-20 09:02 UTC, asas1asas200 commented on src/routes/profile/index.js
> +    res.status(200).send("OK");
You had better check if received user id is same as current logined user.
It causes a critical security issue.

2022-11-20 09:02 UTC, asas1asas200 commented on src/views/profile/home.ejs
> +    <script src="/js/profile/edit.js"></script>
Where is this file?

2022-11-20 09:31 UTC, Argentum11 commented on src/routes/profile/index.js
> +  res.render("profile/home", { title: "profile edit", data: currentUser });
Ok, I fixed this in the following commit

2022-11-20 09:31 UTC, Argentum11 commented on src/routes/profile/index.js
> +    res.status(200).send("OK");
Ok, I fixed this in the following commit

2022-11-20 09:32 UTC, Argentum11 commented on src/views/profile/home.ejs
> +    <script src="/js/profile/edit.js"></script>
Sorry, I forgot to add the entire folder, I add it in the following commit

2022-11-20 09:48 UTC, asas1asas200 commented on src/routes/profile/index.js
> +    }
Return `403` in `else` section.

2022-11-20 09:52 UTC, asas1asas200 commented on src/routes/profile/index.js
> +      let user = await User.findOne({ id: req.params.id }).lean();
This part is so weird.
Use `req.params.id` is fine, and the `req.body.data.id` is not needed because you can identify user by params.

2022-11-20 10:02 UTC, Argentum11 commented on src/routes/profile/index.js
> +      let user = await User.findOne({ id: req.params.id }).lean();
Got it

2022-11-20 10:02 UTC, Argentum11 commented on src/routes/profile/index.js
> +    }
Ok, I fixed this in the following commit

2022-11-20 19:40 UTC, asas1asas200 commented
So far, so good.

I made some changes in this PR.

I think that profile page should also display user verification status(including email and account verification).

Password can write as below:
```
Old password: [        ]
New password: [        ]
Confirm password: [        ]
```
If a user want to change his pw, he/she must fill old password and type twice new password.
In backend, if `req.data.body` contains `oldPassword`, make sure the old password match with db then update it or return an error.

Please pull my commit and modified that.

2022-11-20 19:44 UTC, asas1asas200 commented on src/routes/profile/index.js
> +    }
It should be `res.status(403).send("403 Forbidden");`

2022-11-21 04:06 UTC, asas1asas200 commented on src/routes/profile/index.js
> +router.post("/:id", async function (req, res, next) {
Consider using HTTP PUT instead to conform to restful API.

2022-11-21 07:33 UTC, Argentum11 commented on src/routes/profile/index.js
> +    }
fixed in [fix return status if userID unmatched](https://github.com/asas1asas200/NTOUClassroomBorrowing/pull/42/commits/03221693d2c815d1628682c15c077cff158d1282)

2022-11-21 07:33 UTC, Argentum11 commented on src/routes/profile/index.js
> +router.post("/:id", async function (req, res, next) {
fixed in [fix edit password to HTTP PUT](https://github.com/asas1asas200/NTOUClassroomBorrowing/pull/42/commits/6879b7f788ca37e06f38bafef5e7064bf72f3c0c)

2022-11-21 07:52 UTC, Argentum11 commented
> So far, so good.
> 
> I made some changes in this PR.
> 
> I think that profile page should also display user verification status(including email and account verification).
> 
> Password can write as below:
> 
> ```
> Old password: [        ]
> New password: [        ]
> Confirm password: [        ]
> ```
> 
> If a user want to change his pw, he/she must fill old password and type new password twice. In backend, if `req.data.body` contains `oldPassword`, make sure the old password match with db then update it or return an error.
> 
> Please pull my commit and modify that.

I'm confused.
I made the three password blocks triggered by the edit password button in [fix profile page wrong data](https://github.com/asas1asas200/NTOUClassroomBorrowing/pull/42/commits/d73bfaeef8c5fcff03188a755b073981f599e220), the reason for the button is that not all users want to edit password, if users didn't press that button, user's password wil not be altered.
But I see that you deleted the button, so I don't understand this content

2022-11-21 08:22 UTC, asas1asas200 commented
> > So far, so good.
> > 
> > I made some changes in this PR.
> > 
> > I think that profile page should also display user verification status(including email and account verification).
> > 
> > Password can write as below:
> > 
> > ```
> > Old password: [        ]
> > New password: [        ]
> > Confirm password: [        ]
> > ```
> > 
> > If a user want to change his pw, he/she must fill old password and type new password twice. In backend, if `req.data.body` contains `oldPassword`, make sure the old password match with db then update it or return an error.
> > 
> > Please pull my commit and modify that.
> 
> I'm confused.
> I made the three password blocks triggered by the edit password button in [fix profile page wrong data](https://github.com/asas1asas200/NTOUClassroomBorrowing/pull/42/commits/d73bfaeef8c5fcff03188a755b073981f599e220), the reason for the button is that not all users want to edit password, if users didn't press that button, user's password wil not be altered.
> But I see that you deleted the button, so I don't understand this content

If user don't want to edit his/her pw, just let the password fields empty, you should check if pw fields are filled while pressing the edit button.

2022-11-28 15:11 UTC, asas1asas200 requested changes

2022-11-28 15:14 UTC, asas1asas200 commented on src/public/js/profile/edit.js
> +    console.log("")
Redundency.

2022-11-30 07:56 UTC, Argentum11 commented on src/public/js/profile/edit.js
> +    console.log("")
> If user don't want to edit his/her pw, just let the password fields empty
The above code is what you asked for, so I made a check to find out if users want to edit his/her pwd, therefore I don't understand why is this redundant

2022-11-30 08:15 UTC, asas1asas200 commented on src/public/js/profile/edit.js
> +    console.log("")
I mean `console.log("")`.

2022-11-30 08:28 UTC, Argentum11 commented on src/public/js/profile/edit.js
> +    console.log("")
Got it

2022-12-18 05:12 UTC, asas1asas200 approved these changes

2022-12-18 05:12 UTC, merged